version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=expense-management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  spring-app:
    build:
      context: .
    container_name: spring-app
    depends_on:
      - postgres
    environment:
      - SECRET_KEY=my-secret-key
      - DATABASE_URL=jdbc:postgresql://host.docker.internal:5432/expense-management
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=123
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
